#!/bin/bash

echo "deb http://apt.opscode.com/ `lsb_release -cs`-0.10 main" | sudo tee /etc/apt/sources.list.d/opscode.list

sudo mkdir -p /etc/apt/trusted.gpg.d
gpg --keyserver keys.gnupg.net --recv-keys 83EF826A
gpg --export packages@opscode.com | sudo tee /etc/apt/trusted.gpg.d/opscode-keyring.gpg > /dev/null


sudo apt-get update -y
sudo apt-get install opscode-keyring -y
sudo apt-get upgrade -y
sudo apt-get install chef -y

sudo mkdir /etc/chef
echo "log_level              :info" > /etc/chef/client.rb
echo "log_location           STDOUT" >> /etc/chef/client.rb
echo "chef_server_url        \'https://api.opscode.com/organizations/att_services\'" >> /etc/chef/client.rb
echo "validation_client_name \'att_services-validator\'" >> /etc/chef/client.rb

echo "{\"run_list\":[\"role[booted]\"]}" > /etc/chef/firstboot.json

chef-client -j /etc/chef/firstboot.json

